import Proofs.Lang
import Proofs.Autom

namespace pumping
open Lang Dfa
variable (Sigma : Type)[Alphabet Sigma]
instance : HPow (Word Sigma) ℕ (Word Sigma)
where hPow := λ x n ↦ List.flatten (x^n)
variable {Sigma : Type}[Alphabet Sigma]

def REG : Set (Lang Sigma)
:= {lang | ∃ A : DFA Sigma, Dfa.L A = lang}
/-
What is a regular language?
A language that can be represented by a DFA (or NFA or RE).
Given a regular language, we may not know the DFA, but we know
that it has some number n of states.
If we have an accepted word of length greater than n, then
it must traverse some nonempty loop in the DFA.
But that must mean that the word traversing this loop multiple
times, is also in the language.
The first loop must occur in the first n steps.
So the repeated substring is also in the first n characters.
So, for all words longer than n,
There exists a nonempty subword within the first n characters
such that the word obtained by repeated or omitting this
subword is also accepted.
-/
theorem pumping_lemma : ∀ L₁ : Lang Sigma,
  L₁ ∈ REG →
    (∃ n : ℕ,
    ∀ w : Word Sigma,
    w.length ≥ n ∧ w ∈ L₁ →
      ∃ x y z : Word Sigma,
      w = x ++ y ++ z ∧
      (x ++ y).length ≤ n ∧
      y.length ≥ 1 ∧
      ∀ m : ℕ, x ++ y^m ++ z ∈ L₁
    ) := by sorry
/-
The pumping lemma is used to show that a language is not regular:
1. Assume L is regular
2. Assume we have a pumping length n
3. We choose w such that w.length ≥ n and w ∈ L
4. Then we show that for _any_ split xyz = w with |xy| ≤ n and |y| ≥ 1,
  There exists some repetition of y's such that xy^mz is not in the language

Example: L = { a^n | n is prime }
1. Assume L is regular.
2. That means we have a pumping length n
3. Let w = a^m where m is the first prime greater than n
4. Let x y z be such that xy = a^p for p ≤ n and y = a^q for 1 ≤ q ≤ p
Now consider x ++ y^s ++ z. What is this word?
xy^sz = x ++ y^s ++ z
x = a^{p-q}
z = a^{m-p}
y^s = a^{s*q}
Thus, xy^sz = a^{(p-q)+(s*q)+(m-p)} = a^{m+(s-1)*q}
-- (p-q)+(s*q)+(m-p) = p-q+m-p+s*q = -q+m+s*q = m+s*q-q = m+(s-1)*q
If we pick s = m+1
then x++y^s++z = a^{m+(m+1-1)*q} = a^{m+m*q} = a^{m(1+q)}
That must must that x++y^s++z is not in L
That contradicts the pumping lemma
That must mean that L is not regular.
-/
end pumping
/-
Context-free grammars (CFG)
A CFG consists of
 - Nonterminal characters
 - Terminal characters
 - A starting character
 - Derivation rules.

Example : simple arithmetic formulas like
a + (a*a)

Let's create a CFG for this language
Nonterminals are E, T, F
Starting symbol: S = E
Terminals here are: a, +, (, *, )
Derivation rules:
E => T
E => E + T
T => F
T => T*F
F => a
F => (E)

How would this generate a formula?
E.g. a + (a*a)
This generated by
E => E + T => E + F
=> E + (E) => E + (T)
=> E + (T*F) => E + (T*a)
=> E + (F*a) => E + (a*a)
=> T + (a*a) => F + (a*a)
=> a + (a*a)

Language of a CFG is all those
words over the terminal characters
such that there exists a chain
of derivations from the starting NT
to that word.
-/
